name: CICD
on:
   workflow_dispatch: 
     inputs:
       environment:
         description: This is the environment value where this workflow runs
         default: 'dev'
         required: true
         type: choice
         options: 
            - dev
            - prod
            - staging
            
jobs:
   code:
     runs-on: ubuntu-latest
     steps: 
       - name: checkout code
         run: echo "Code Check"

   build:
      needs: code
      runs-on: ubuntu-latest
      steps:
         - name: build the code
           run: echo "docker build"

   test:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - name: test the container
           run: echo "testing the container"

   deploy:
       if: inputs.environment == 'dev'
       needs: test
       runs-on: ubuntu-latest
       steps:
          - name: deploy the application
            run: echo "deploying the application on the ec2 instance"
