name: Deploy Flask App

on:
  workflow_run:
          workflows: ["docker build & push"]
          types: [completed]
          branches:
              - main

jobs:
    deploy:
         env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

         runs-on: self-hosted

         steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Deploy with Docker Compose
              run: docker compose down && docker compose up -d --build --force-recreate --pull always
